export const fakePointages2 = [
  {
    date: new Date(2021, 9, 4),
    moment: 0,
    valeur: 4,
    affaireId: 5,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 4),
    moment: 1,
    valeur: 3,
    affaireId: 5,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 5),
    moment: 0,
    valeur: 3,
    affaireId: null,
    motifAbsenceId: 5,
  },
  {
    date: new Date(2021, 9, 5),
    moment: 1,
    valeur: 3,
    affaireId: null,
    motifAbsenceId: 5,
  },
  {
    date: new Date(2021, 9, 6),
    moment: 0,
    valeur: 4.5,
    affaireId: 5,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 6),
    moment: 1,
    valeur: 2.5,
    affaireId: 11,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 7),
    moment: 0,
    valeur: 5,
    affaireId: 5,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 7),
    moment: 1,
    valeur: 2,
    affaireId: 11,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 8),
    moment: 0,
    valeur: 4,
    affaireId: 5,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 8),
    moment: 1,
    valeur: 0,
    affaireId: null,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 9),
    moment: 0,
    valeur: 0,
    affaireId: null,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 9),
    moment: 1,
    valeur: 0,
    affaireId: null,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 10),
    moment: 0,
    valeur: 0,
    affaireId: null,
    motifAbsenceId: null,
  },
  {
    date: new Date(2021, 9, 10),
    moment: 1,
    valeur: 0,
    affaireId: null,
    motifAbsenceId: null,
  },
];
